security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        admin_in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$hlylYTecX5gXogRfxBE1He379gmLY9dhfNyulx9cPPcFfbo6zMEXa'
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        admin:
            pattern: ^/admin
            provider: admin_in_memory
            form_login:
                login_path: app_admin_login
                check_path: app_admin_login
                default_target_path: /admin
                username_parameter: _username
                password_parameter: _password
            logout:
                path: app_admin_logout
                target: app_admin_login

        main:
            lazy: true
            provider: admin_in_memory

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
