<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260305100156 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, article VARCHAR(100) NOT NULL, model VARCHAR(255) NOT NULL, ean VARCHAR(50) DEFAULT NULL, description TEXT DEFAULT NULL, brand VARCHAR(255) DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, stock INT NOT NULL, pvpr NUMERIC(10, 3) DEFAULT NULL, iva_tecno VARCHAR(10) DEFAULT NULL, obsolete BOOLEAN NOT NULL, digital_canon NUMERIC(10, 2) DEFAULT NULL, slug VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, family_id INT NOT NULL, subfamily_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04ADC35E566A ON product (family_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD5731FD53 ON product (subfamily_id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADC35E566A FOREIGN KEY (family_id) REFERENCES family (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD5731FD53 FOREIGN KEY (subfamily_id) REFERENCES subfamily (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04ADC35E566A');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD5731FD53');
        $this->addSql('DROP TABLE product');
    }
}
