# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Command\FetchProductImagesCommand:
        arguments:
            $icecatUser: '%env(ICECAT_USER)%'
            $icecatPass: '%env(ICECAT_PASS)%'
